version: '3'
services:
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/app"
  employees:
    build: services/employees
    ports:
      - "8080:8080"

# volumes:
#   frontend:
#     external: true